version: '3'
services:
    hackedweb:
        build:
            context: ./hackedweb
            dockerfile: Dockerfile
        ports:
            - "8889:80"
    openplc:
        build:
            context: ./openplc
            dockerfile: Dockerfile
        ports:
            - "8890:8080"
